### ISSUE TITLE
Music playing from Plexamp only updates time and not title / artist.

### ISSUE THREAD

**Issue by Glitchy02** [Arno500/plex-richpresence#13]
Hi, 
When playing music on Plexamp, currentPlayState.session seems to only get set on the first song, with subsequent songs not getting their titles/artists updated.
Seems to work fine on Firefox Web though.

The last release did improve the time remaining/elapsed though, which is much appreciated!!

Thanks, keep up the good work!

**Comment by Arno500** [comment]
Hi @Glitchy02!
After some digging, I found that indeed, Plexamp always keeps the same session (probably because of that gapless magic), and thus, Plex Rich Presence keeps the same entry in the cache. I made sure that if the key of the media being played change, then simple update the session!
The new release [1.6.2](https://github.com/Arno500/plex-richpresence/releases/tag/1.6.2) should fix your issue (you can relaunch to auto update).
