### ISSUE TITLE
Is it possible to use this on MacBook m2 chip

### ISSUE THREAD

**Issue by Josja2030** [Arno500/plex-richpresence#21]
hi I use to use this on windows and worked amazingly however. I moved to MacBook Air 2023 m2 chip, and wondered how I could download ur rich presence for Plex on this? or if u know any one else who does this but has Mac support thanks

**Comment by Arno500** [comment]
Hello @Josja2030 ,

Indeed, nothing should explicitely stop you from running this. It is pretty annoying to build something for macOS (due to the mandatory signature for good UX, hard to build without a real mac when you have native dependencies, etc.) so I am not uploading macOS builds because I cannot make them.

But you have everything you need to build it by yourself:
- you need to download Go
- you will need to put the built binary in a .app folder with the following structure: https://github.com/nekr0z/systray?tab=readme-ov-file#macos
- you also probably need the macOS SDK
- I don't think you need any particular dependency, but maybe you do, I don't know

Good luck on that!
