### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by rafaeldamasceno** [Arno500/plex-richpresence#4]
Sad to say that I'm back, only this time I have no information at all about the crash. The logs don't show anything interesting.

Plex for Windows: Version 1.39.1.2763-300bb607
Plex Media Server: Version 1.25.2.5319

**Comment by Arno500** [comment]
Yeah, about to squash some more bugs!
Question: was it after your computer went to sleep? Or after a disconnect? Or after a network card was switched on/off (like switching from WiFi to nothing or to Ethernet)? 
Because I know that the app does crash without any logs in these cases, and I don't know why, yet.

**Comment by nicholasyoannou** [comment]
Got some additional info linking to this! The app crashes for me when I connect to a VPN, lose connection to WiFi, turn off WiFi, or do anything in any way that loses connection to the internet. You should be able to add a way for the Plex app to keep retrying after a minute (do this for five attempts). If all attempts fail, they could right click on the Plex rich presence icon and hit 'Connect' to manually retry.

**Comment by Arno500** [comment]
Thanks for the report. It seems the issue is linked to a lost of network connectivity.
Personally, I have a similar issue when putting my computer to sleep. The network card gets disabled and it panic because there is a lot of attempts to read the WebSocket (leading to the crash).
I'm currently investigating this with the addition of a recovery mecanism with backoff :) (the best is to recovery fully automatically, not with a user interaction)

**Comment by Arno500** [comment]
Hello @nicholasyoannou and @rafaeldamasceno 
You may try the new release 1.3.0 that should fix this issue! https://github.com/Arno500/plex-richpresence/releases/tag/1.3.0
Please tell me if the issue can be closed (in case everything is fine, of course)
