### ISSUE TITLE
Suggestion - add so album photo comes up instead of Plex logo

### ISSUE THREAD

**Issue by nicholasyoannou** [Arno500/plex-richpresence#6]
Would look awesome with this suggestion, https://github.com/Ombrelin/plex-rich-presence/ manages to do it but their one doesn't work with the Plex Windows App, yours does though and it's only like ....7 MB compared to their 70MB one.

Anyways thanks for this app, it's amazing! That's the only thing personally I think is missing, album photo on rich presence instead of the plex icon.

![image](https://user-images.githubusercontent.com/29736141/151675600-4f4ed34b-1626-458c-8969-933db2733fb9.png)
![image](https://user-images.githubusercontent.com/29736141/151675611-3d190dd1-5d02-4d5d-9309-3ef286098719.png)
So that album image instead of the plex icon. Would be great, thanks again!

**Comment by Arno500** [comment]
Hello @nicholasyoannou 
That'd be a great idea!
I may explore uploading also TV Show artworks and movies covers in the future, but this is the most interesting for album arts

Personal note: https://discord.com/developers/docs/reference#uploading-files

**Comment by Ravencentric** [comment]
Discord now allows the use of links for images.
Can possibly fetch links for TV Shows, Movies, and Music from their respective databases.
Example: 
https://github.com/PvtTyphoon/lfm-rich-presence
https://github.com/jeffvli/sonixd

**Comment by Arno500** [comment]
Interesting point! I still want to fix the Home issue before (I have a feeling it should be simple), but I don't have any free time until summer :/
I'll certainly provide an option to either use the "default" picture like now or the cover art like this :)
But coming soon!
Thanks for the examples

**Comment by Ravencentric** [comment]
Glad to hear that! Thank you for your work ^_^

**Comment by TheFeelTrain** [comment]
Is this still being worked on?

**Comment by Arno500** [comment]
Hello @TheFeelTrain !
I've been looking at that exactly two days ago. I'm currently trying to figure out how to make Discord itself host the image and not external services. But we're getting there!

**Comment by nicholasyoannou** [comment]
Hey @Arno500 👋

Glad your still working on this. I’ve got a suggestion, why don’t you use Imgurs’ API and set the URL to the photo on Imgur? If that’s too API straining, what about converting the Plex album images to data strings and using them somehow?
Gotta be careful because the actual album photo URL has a token parameter in the URL itself, don’t want someone to get control of my Plex account.

Just letting you know of this because I’ve done some experimenting in the past using a PlexAPI that was able to get image URLs.

**Comment by Arno500** [comment]
I thought about that, but we would spam Imgurs each time a media change, and I can guess we would get rate limited, as you can guess (plus I would need to include an API key inside the program itself, or ask people to input one, but I don't like that).
For the datastring, impossible, Discord doesn't allow that. But what I found, is that Discord will ALWAYS proxy the image, meaning that the client-side URL will simply be a Discord Media URL, making it safe. It means I'm able to feed directly the URL of the media with direct access to the server, and it should be fine.
Main drawback: I cannot do that for offline servers, unfortunately (but is it really common? I guess not, but still). Note that I cannot include a Discord URL to a file, Discord will simply rewrite the URL in a strange way, probably to prevent security flaws or scams.

**Comment by nicholasyoannou** [comment]
Offline servers are fair enough, to get around the limitation the user could provide their own API key possibly (as technically offline servers aren't very common -- the purpose of a plex media server is for it to be online so its accessible from anywhere). 
Glad Discord cloaks the URL so there's no mad security issue. 
Regarding spamming the API, there is a little problem with that, makes sense for offline servers. Maybe convert them to data strings and then find an API online that converts data strings to images, and then set that URL as the cover image? Not sure if it's possible but it might be 🤷‍♂️

**Comment by Arno500** [comment]
I also want to dodge the fact that things may break if that API breaks, actually. I would like to rely on the least services possible (besides Discord and Plex, of course).

Actually, I just thought about it, but my app cannot work for offline scenarios because I need to authenticate to central Plex auth, I don't manage direct authentication, which makes everything “easier” and more secure.

**Comment by Arno500** [comment]
Okay, after a bit more fiddling, I took your idea @nicholasyoannou and upload the images to Imgur (hoping we don't reach quotas, but since it's a small project, should be fine). It works with any server, exposed or not (but still adopted of course) and keep the confidentiality at maximum (I'm not even giving the URL to Imgur to download your pictures, I'm downloading them in the app, then uploading them manually).

![image](https://user-images.githubusercontent.com/6131706/199154497-136b761f-cd51-4af6-92f9-1a365b68f348.png)

It was released in just now: https://github.com/Arno500/plex-richpresence/releases/tag/1.6.0
The auto updater feature should push it to you now if you restart the application!
